### ISSUE TITLE
Joining a raid appointment via button (message component)

### ISSUE THREAD

**Issue by thoenissen** [thoenissen/Scruffy#21]
**Describe the solution you'd like**
It should be added buttons to the raid appointment message. These buttons can be used to join or leave the raid appointment.

Task list:
- [x] Adding the message component when refreshing the appointment message
- [x] Implementation of the buttons
- [x] Disabling the buttons when the appointment starts

**Comment by MarkusGeorgi** [comment]
yo! will das auch machen
