### ISSUE TITLE
Fractal lfg rework

### ISSUE THREAD

**Issue by thoenissen** [thoenissen/Scruffy#32]
The fractal lfg should be reworked to support the following features:

- [ ] Support of T1, T2, T3, T4, CM
- [ ] Remove default reminder
- [ ] Remove deadline
- [ ] Add buttons (join, leave, reminder)

**Comment by thoenissen** [comment]
The fractal lfg will be replaced by the new general lfg tool. (#35 )
